--                             HOSPITALITY INSIGHT
 
 SHOW triggers ;
 

-- TOTAL REVENUE --
SELECT CONCAT("$",ROUND(SUM(REVENUE_REALIZED)/1000000),"M") AS TOTAL_REVENUE FROM fact_bookings;

-- TOTAL BOOKINGS -- 
SELECT CONCAT(ROUND((COUNT(Booking_ID)/1000),2),"K") AS TOTAL_BOOKINGS FROM fact_bookings;

-- OCCUPANCY RATE --
WITH SUCCESSFUL_BOOKINGS AS 
(SELECT SUM(SUCCESSFUL_BOOKINGS) AS TOTAL_SUCCESSFUL_BOOKINGS,
        SUM(CAPACITY) AS TOTAL_CAPACITY FROM fact_aggregated_bookings)

SELECT CONCAT(ROUND(((TOTAL_SUCCESSFUL_BOOKINGS/TOTAL_CAPACITY)*100),2),"%") AS OCCUPANCY_RATE
	   FROM SUCCESSFUL_BOOKINGS;
       
-- CANCELATION RATE --
WITH CANCELLED_BOOKINGS AS (
SELECT COUNT(BOOKING_STATUS) AS TOTAL_CANCELLED_BOOKINGS
	   FROM FACT_BOOKINGS
	   WHERE BOOKING_STATUS="CANCELLED")
,TOTAL_BOOKING AS
(SELECT COUNT(BOOKING_ID) AS TOTAL_BOOKINGS FROM FACT_BOOKINGS)

SELECT CONCAT(ROUND(((TOTAL_CANCELLED_BOOKINGS/TOTAL_BOOKINGS)*100),2),"%") AS CANCELATION_RATE
	   FROM CANCELLED_BOOKINGS,TOTAL_BOOKING;
       
-- AVG GUEST RATING --
SELECT ROUND(AVG(RATINGS_GIVEN),0) AS AVG_RATING FROM fact_bookings;


# CLASS WISE REVENUE
SELECT ROOM_CLASS,
       CONCAT("$",ROUND((SUM(REVENUE_REALIZED)/1000000),2),"M") AS TOTAL_REVENUE
       FROM dim_rooms
	   JOIN fact_bookings 
       ON dim_rooms.ROOM_ID=fact_bookings.room_category
       GROUP BY ROOM_CLASS
       ORDER BY TOTAL_REVENUE;
       
# BOOKING BY PLATFORM 
SELECT BOOKING_PLATFORM,
       COUNT(*) AS BOOKINGS_OCCURED
       FROM fact_bookings
       GROUP BY BOOKING_PLATFORM
       ORDER BY BOOKINGS_OCCURED DESC;
       
# REVENUE TREND WEEK WISE
SELECT WEEK(BOOKING_DATE) AS WEEK_NO,(SUM(REVENUE_REALIZED)/1000) AS TOTAL_REVENUE
       FROM fact_bookings
       GROUP BY WEEK_NO
       ORDER BY WEEK_NO;
       
# BOOKING TREND WEEK WISE
SELECT WEEK(BOOKING_DATE) AS WEEK_NO,COUNT(BOOKING_ID) AS TOTAL_BOOKINGS
       FROM fact_bookings
       GROUP BY WEEK_NO
       ORDER BY WEEK_NO;

 # AVERAGE GUEST RATING BY HOTEL 
 SELECT PROPERTY_NAME,ROUND(AVG(RATINGS_GIVEN),1) AS RATINGS FROM dim_hotels
	    JOIN fact_bookings 
        ON dim_hotels.PROPERTY_ID=fact_bookings.property_id
        GROUP BY property_name
        ORDER BY RATINGS DESC;
 
 # STATE WISE REVENUE
 SELECT CITY,(SUM(REVENUE_REALIZED)/1000000) AS REVENUE_GENRATED 
	    FROM DIM_HOTELS
        JOIN FACT_BOOKINGS
        ON DIM_HOTELS.PROPERTY_ID=FACT_BOOKINGS.PROPERTY_ID
        GROUP BY CITY
        ORDER BY REVENUE_GENRATED DESC;
 
# STATE AND HOTEL WISE REVENUE
SELECT CITY,PROPERTY_NAME,(SUM(REVENUE_REALIZED)/1000000) AS REVENUE_GENRATED FROM DIM_HOTELS
	   JOIN FACT_BOOKINGS
       ON DIM_HOTELS.PROPERTY_ID=FACT_BOOKINGS.PROPERTY_ID
       GROUP BY CITY,PROPERTY_NAME
       ORDER BY CITY,PROPERTY_NAME;

# WEEKDAY VS WEEKEND REVENUE
WITH WEEK_DAY AS (
	SELECT weekday(BOOKING_DATE) AS WEEK_DAY,
    SUM(revenue_realized) AS TOTAL_REVENUE FROM fact_bookings
	WHERE weekday(BOOKING_DATE) IN (5,6)
	GROUP BY WEEK_DAY
    )
SELECT WEEK_DAY,TOTAL_REVENUE FROM WEEK_DAY;

# WEEKDAY VS WEEKEND BOOKINGS     
SELECT WEEKDAY(BOOKING_DATE) AS WEEK_DAY, COUNT(BOOKING_ID) AS TOTAL_BOOKINGS 
       FROM fact_bookings
       GROUP BY WEEK_DAY;


	







  





	




